/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.console.gui;

import model.validations.UserDataValidations;
import javax.swing.*;

/**
 *
 * @author saulrodfer
 */
public class JFrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    
       public JFrameRegister(){
        initComponents();
        initConfig();
    }
    private void initConfig(){
        resetFields();    
    }
    private void resetFields(){
        jLabelErrorName.setVisible(false);
        jLabelErrorNIF.setVisible(false);
        jLabelErrorEmail.setVisible(false);
        jLabelErrorBirth.setVisible(false);
        jLabelErrorSurname.setVisible(false);
        jLabelErrorPassword.setVisible(false);

        
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jPanelPassword.setName("");
        jTextFieldBirth.setText("");
        jTextFieldSurname.setText("");
        jTextFieldNameAge.setText("");
         jTextFieldEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPassword = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelBirth = new javax.swing.JLabel();
        jTextFieldBirth = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldNameAge = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonValidation1 = new javax.swing.JButton();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelErrorNIF = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelErrorBirth = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabelErrorSurname = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelErrorPassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica Swing");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelPassword.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(169, 133, 133));
        jLabelTitle.setText("Registro Trendy08s");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelName.setText("Nombre: ");

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelNIF.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNIF.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNIF.setText("NIF: ");

        jTextFieldNIF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmail.setText("Email: ");

        jLabelBirth.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelBirth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelBirth.setText("Fecha Nac.: ");

        jTextFieldBirth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelAge.setText("Edad : ");

        jTextFieldNameAge.setEditable(false);
        jTextFieldNameAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonClear.setBackground(new java.awt.Color(255, 153, 153));
        jButtonClear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(153, 0, 51));
        jButtonClear.setText("Limpiar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonValidation1.setBackground(new java.awt.Color(153, 255, 153));
        jButtonValidation1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonValidation1.setForeground(new java.awt.Color(0, 153, 153));
        jButtonValidation1.setText("Enviar");
        jButtonValidation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidation1ActionPerformed(evt);
            }
        });

        jLabelErrorName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorName.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorName.setText("Nombre Introducido Incorrecto");

        jLabelErrorNIF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorNIF.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorNIF.setText("NIF Introducido Incorrecto");

        jLabelErrorEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorEmail.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorEmail.setText("Email Introducido Incorrecto");

        jLabelErrorBirth.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorBirth.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorBirth.setText("Fecha Introducida Incorrecta");
        jLabelErrorBirth.setToolTipText("");

        jLabelSurname.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSurname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSurname.setText("Apellido: ");

        jTextFieldSurname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelErrorSurname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorSurname.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorSurname.setText("Apellido Introducido Incorrecto");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelPassword.setText("Contraseña:");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelErrorPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelErrorPassword.setForeground(new java.awt.Color(153, 0, 0));
        jLabelErrorPassword.setText("Mínimo 8 longitud, 1 Número,1 Mayúscula, 1 Minúscula, 1 Carácter especial.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo231q.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanelPasswordLayout = new javax.swing.GroupLayout(jPanelPassword);
        jPanelPassword.setLayout(jPanelPasswordLayout);
        jPanelPasswordLayout.setHorizontalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelNIF)))
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrorNIF)
                                    .addComponent(jLabelErrorName))
                                .addGap(317, 317, 317))
                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasswordLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelAge)
                                            .addComponent(jButtonValidation1))
                                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jButtonClear))
                                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldNameAge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPasswordField1)
                                            .addComponent(jTextFieldNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                        .addGap(18, 94, Short.MAX_VALUE)
                                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelBirth, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                        .addComponent(jLabelErrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorSurname)
                            .addComponent(jLabelErrorEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorBirth)))
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTitle)
                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jLabelSurname)))
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPasswordLayout.setVerticalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabelTitle)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelName)
                        .addComponent(jLabelSurname)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorName)
                    .addComponent(jLabelErrorSurname))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNIF)
                        .addComponent(jLabelEmail)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorNIF)
                    .addComponent(jLabelErrorEmail))
                .addGap(21, 21, 21)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPassword)
                        .addComponent(jTextFieldBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBirth)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorPassword)
                    .addComponent(jLabelErrorBirth))
                .addGap(45, 45, 45)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldNameAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidation1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(292, 292, 292))
        );

        getContentPane().add(jPanelPassword, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidation1ActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String date = jTextFieldBirth.getText();
        String surname = jTextFieldSurname.getText();
        String password = jPasswordField1.getName();

        if(!UserDataValidations.checkName(name)){
            jLabelErrorName.setVisible(true);
        }
        if(!UserDataValidations.checkId(1, nif)){
            jLabelErrorNIF.setVisible(true);
        }
        if(!UserDataValidations.checkEmail(email)){
            jLabelErrorEmail.setVisible(true);
        }
        if(!UserDataValidations.checkFormatDate(date)){
            jLabelErrorBirth.setVisible(true);
        }
        else{
            int age = UserDataValidations.calculateAge(date);
            String ageStr = String.valueOf(age);
            jTextFieldNameAge.setText(ageStr);
        }
        if(!UserDataValidations.checkSurname(surname)){
            jLabelErrorSurname.setVisible(true);
        }
        if(!UserDataValidations.checkPassword(password)){
            jLabelErrorPassword.setVisible(true);
        }
    }//GEN-LAST:event_jButtonValidation1ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_jButtonClearActionPerformed

 
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidation1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorBirth;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorNIF;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorPassword;
    private javax.swing.JLabel jLabelErrorSurname;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelPassword;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldBirth;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNameAge;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
